### ISSUE TITLE
Python Code to Save Trained Model?

### ISSUE THREAD

**Issue by ghost** [maartensap/riveter-nlp#9]
Hi! I am trying to save a trained riveter model in Python, I see the code do this in Google Colab but am having issues saving with Python. I run the following code:
`riveter.save('/Users/cristinazito/Desktop/riveter code/riveter-nlp/riveter/data/riveter.power5.pkl')`

And receive this error:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cristinazito/Desktop/riveter code/riveter-nlp/riveter/riveter.py", line 93, in save
    pickle.dump(self, file, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class 'riveter.riveter.Riveter'>: import of module 'riveter.riveter' failed
>>> ")
  File "<string>", line 1
    ")
      ^
SyntaxError: EOL while scanning string literal
>>>`

Seems to be a picking issue since the pickle.dump() function fails. Can you please advise?

**Comment by maria-antoniak** [comment]
Hi! Are you having this issue in the Colab notebook or on your local machine?
